version: '3.1'
services:
  stats-server:
    build: stats/stats-service
    image: stats_service
    container_name: stats_service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=explorer

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=explorer
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm_stats

  ewm-service:
    build: main-service
    image: main_service
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=explorer
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=explorer
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm_main
